[project]
name = "joern-mcp"
version = "0.1.0"
description = "A simple Joern MCP Server."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.1",
    "fastmcp>=2.1.0",
    "requests>=2.32.3",
]
